#ifndef BOARD_H
#define BOARD_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes */


/* Define */
/* LED */
#define	LED_GPIO_PER_CLOCK			(RCM_AHB_PERIPH_GPIOF)

#define	LED1_GPIO_PIN						(GPIO_PIN_4)
#define	LED1_GPIO_PORT					GPIOF

#define	LED2_GPIO_PIN						(GPIO_PIN_5)
#define	LED2_GPIO_PORT					GPIOF



/* BUZZER */
#define	BUZZER_GPIO_PER_CLOCK		(RCM_AHB_PERIPH_GPIOA)

#define	BUZZER_GPIO_PIN					(GPIO_PIN_9)
#define	BUZZER_GPIO_PORT				GPIOA



/* OUTPUT */
#define	OUTPUT_GPIO_PER_CLOCK		(RCM_AHB_PERIPH_GPIOC)

#define	CON_VST_GPIO_PIN				(GPIO_PIN_5)
#define	CON_VST_GPIO_PORT				GPIOC



/* BDC */
#define	BDC_GPIO_PER_CLOCK				(RCM_AHB_PERIPH_GPIOA|RCM_AHB_PERIPH_GPIOF)

#define	BDC_nFAULT_GPIO_PIN				(GPIO_PIN_6)
#define	BDC_nFAULT_GPIO_PORT			GPIOF

#define	BDC_nSLP_GPIO_PIN					(GPIO_PIN_7)
#define	BDC_nSLP_GPIO_PORT				GPIOF

#define	BDC_BRAKE_GPIO_PIN				(GPIO_PIN_8)
#define	BDC_BRAKE_GPIO_PORT				GPIOA



/* HALL */
#define	HALL_GPIO_PER_CLOCK				(RCM_AHB_PERIPH_GPIOA)

#define	HALL_1_GPIO_PIN						(GPIO_PIN_7)
#define	HALL_1_GPIO_PORT					GPIOA

#define	HALL_2_GPIO_PIN						(GPIO_PIN_6)
#define	HALL_2_GPIO_PORT					GPIOA



/* ADC */
#define	ADC_GPIO_PER_CLOCK			(RCM_AHB_PERIPH_GPIOC)

#define	ADC_CH10_GPIO_PIN				(GPIO_PIN_0)
#define	ADC_CH10_GPIO_PORT			GPIOC

#define	ADC_CH11_GPIO_PIN				(GPIO_PIN_1)
#define	ADC_CH11_GPIO_PORT			GPIOC

#define	ADC_CH12_GPIO_PIN				(GPIO_PIN_2)
#define	ADC_CH12_GPIO_PORT			GPIOC

#define	ADC_CH13_GPIO_PIN				(GPIO_PIN_3)
#define	ADC_CH13_GPIO_PORT			GPIOC



/* CAN */
#define	CAN_GPIO_PER_CLOCK			(RCM_AHB_PERIPH_GPIOA)

#define	CAN_RX_GPIO_PIN					(GPIO_PIN_11)
#define	CAN_RX_GPIO_PORT				GPIOA
#define CAN_RX_PIN_SOURCE   	  GPIO_PIN_SOURCE_11
#define CAN_RX_GPIO_AF					GPIO_AF_PIN4

#define	CAN_TX_GPIO_PIN					(GPIO_PIN_12)
#define	CAN_TX_GPIO_PORT				GPIOA
#define CAN_TX_PIN_SOURCE   	  GPIO_PIN_SOURCE_12
#define CAN_TX_GPIO_AF					GPIO_AF_PIN4

#define	CAN_STB_GPIO_PIN				(GPIO_PIN_10)
#define	CAN_STB_GPIO_PORT				GPIOA



//#define	CAN_GPIO_PER_CLOCK			(RCM_AHB_PERIPH_GPIOB)

//#define	CAN_RX_GPIO_PIN					(GPIO_PIN_8)
//#define	CAN_RX_GPIO_PORT				GPIOB
//#define CAN_RX_PIN_SOURCE   	  GPIO_PIN_SOURCE_8
//#define CAN_RX_GPIO_AF					GPIO_AF_PIN1

//#define	CAN_TX_GPIO_PIN					(GPIO_PIN_9)
//#define	CAN_TX_GPIO_PORT				GPIOB
//#define CAN_TX_PIN_SOURCE   	  GPIO_PIN_SOURCE_9
//#define CAN_TX_GPIO_AF					GPIO_AF_PIN1



/* USART */
#define	USART1_GPIO_PER_CLOCK			(RCM_AHB_PERIPH_GPIOB)

#define	USART1_TX_GPIO_PIN				(GPIO_PIN_6)
#define	USART1_TX_GPIO_PORT				GPIOB
#define USART1_TX_PIN_SOURCE   	  GPIO_PIN_SOURCE_6
#define USART1_TX_GPIO_AF					GPIO_AF_PIN0

#define	USART1_RX_GPIO_PIN				(GPIO_PIN_7)
#define	USART1_RX_GPIO_PORT				GPIOB
#define USART1_RX_PIN_SOURCE   	 	GPIO_PIN_SOURCE_7
#define USART1_RX_GPIO_AF					GPIO_AF_PIN0

//#define	USART1_GPIO_PER_CLOCK			(RCM_AHB_PERIPH_GPIOA)

//#define	USART1_TX_GPIO_PIN				(GPIO_PIN_9)
//#define	USART1_TX_GPIO_PORT				GPIOA
//#define USART1_TX_PIN_SOURCE   	  GPIO_PIN_SOURCE_9
//#define USART1_TX_GPIO_AF					GPIO_AF_PIN1

//#define	USART1_RX_GPIO_PIN				(GPIO_PIN_10)
//#define	USART1_RX_GPIO_PORT				GPIOA
//#define USART1_RX_PIN_SOURCE   	 	GPIO_PIN_SOURCE_10
//#define USART1_RX_GPIO_AF					GPIO_AF_PIN1




/* TMR1_CH */
#define	TMR_PWM_GPIO_PER_CLOCK			(RCM_AHB_PERIPH_GPIOC|RCM_AHB_PERIPH_GPIOD)

#define	TMR1_CH1_GPIO_PIN						(GPIO_PIN_10)
#define	TMR1_CH1_GPIO_PORT					GPIOC
#define TMR1_CH1_PIN_SOURCE       	GPIO_PIN_SOURCE_10
#define TMR1_CH1_GPIO_AF          	GPIO_AF_PIN2

#define	TMR1_CH2_GPIO_PIN						(GPIO_PIN_11)
#define	TMR1_CH2_GPIO_PORT					GPIOC
#define TMR1_CH2_PIN_SOURCE       	GPIO_PIN_SOURCE_11
#define TMR1_CH2_GPIO_AF          	GPIO_AF_PIN2

#define	TMR1_CH3_GPIO_PIN						(GPIO_PIN_12)
#define	TMR1_CH3_GPIO_PORT					GPIOC
#define TMR1_CH3_PIN_SOURCE       	GPIO_PIN_SOURCE_12
#define TMR1_CH3_GPIO_AF          	GPIO_AF_PIN2

#define	TMR1_CH4_GPIO_PIN						(GPIO_PIN_2)
#define	TMR1_CH4_GPIO_PORT					GPIOD
#define TMR1_CH4_PIN_SOURCE       	GPIO_PIN_SOURCE_2
#define TMR1_CH4_GPIO_AF          	GPIO_AF_PIN2



/* SPI */
#define	SPI_GPIO_PER_CLOCK				(RCM_AHB_PERIPH_GPIOA|RCM_AHB_PERIPH_GPIOB)

#define	SPI1_NSS_GPIO_PIN					(GPIO_PIN_15)
#define	SPI1_NSS_GPIO_PORT				GPIOA
#define SPI1_NSS_PIN_SOURCE       GPIO_PIN_SOURCE_15
#define SPI1_NSS_GPIO_AF          GPIO_AF_PIN0

#define	SPI1_SCK_GPIO_PIN					(GPIO_PIN_3)
#define	SPI1_SCK_GPIO_PORT				GPIOB
#define SPI1_SCK_PIN_SOURCE       GPIO_PIN_SOURCE_3
#define SPI1_SCK_GPIO_AF          GPIO_AF_PIN0

#define	SPI1_MISO_GPIO_PIN				(GPIO_PIN_4)
#define	SPI1_MISO_GPIO_PORT				GPIOB
#define SPI1_MISO_PIN_SOURCE			GPIO_PIN_SOURCE_4
#define SPI1_MISO_GPIO_AF					GPIO_AF_PIN0

#define	SPI1_MOSI_GPIO_PIN				(GPIO_PIN_5)
#define	SPI1_MOSI_GPIO_PORT				GPIOB
#define SPI1_MOSI_PIN_SOURCE			GPIO_PIN_SOURCE_5
#define SPI1_MOSI_GPIO_AF					GPIO_AF_PIN0



/* –›√ﬂŒﬁπÿ“˝Ω≈≈‰÷√ */
#define	SLEEP_GPIO_PER_CLOCK			(RCM_AHB_PERIPH_GPIOA|RCM_AHB_PERIPH_GPIOB|RCM_AHB_PERIPH_GPIOC|RCM_AHB_PERIPH_GPIOD)

#define	SLEEP_GPIOA_PIN						(GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3|GPIO_PIN_4|GPIO_PIN_5|GPIO_PIN_6|GPIO_PIN_7|GPIO_PIN_9|GPIO_PIN_15)
//#define	SLEEP_GPIOA_PIN						(GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3|GPIO_PIN_4|GPIO_PIN_5|GPIO_PIN_6|GPIO_PIN_7|GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10|GPIO_PIN_11|GPIO_PIN_12|GPIO_PIN_15)
#define	SLEEP_GPIOA_PORT					GPIOA

#define	SLEEP_GPIOB_PIN						(GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3|GPIO_PIN_4|GPIO_PIN_5|GPIO_PIN_6|GPIO_PIN_7|GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10|GPIO_PIN_11|GPIO_PIN_12|GPIO_PIN_13|GPIO_PIN_14|GPIO_PIN_15)
#define	SLEEP_GPIOB_PORT					GPIOB

#define	SLEEP_GPIOC_PIN						(GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3|GPIO_PIN_4|GPIO_PIN_6|GPIO_PIN_7|GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10|GPIO_PIN_11|GPIO_PIN_12|GPIO_PIN_13|GPIO_PIN_14|GPIO_PIN_15)
//#define	SLEEP_GPIOC_PIN							(GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3|GPIO_PIN_4|GPIO_PIN_5|GPIO_PIN_6|GPIO_PIN_7|GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10|GPIO_PIN_11|GPIO_PIN_12|GPIO_PIN_13|GPIO_PIN_14|GPIO_PIN_15)
#define	SLEEP_GPIOC_PORT					GPIOC

#define	SLEEP_GPIOD_PIN						(GPIO_PIN_2)
#define	SLEEP_GPIOD_PORT					GPIOD

#define	SLEEP_GPIOF_PIN						(GPIO_PIN_4|GPIO_PIN_5|GPIO_PIN_6)
#define	SLEEP_GPIOF_PORT					GPIOF

/* Enum */ 



/* Struct */ 







#ifdef __cplusplus
}
#endif

#endif /* */
